use bdvirtual;
INSERT INTO CadFun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES (12, 'CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00);
INSERT INTO CadFun
VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 1985.75);
INSERT INTO CadFun
VALUES (7, 'APARECIDA SILVA', '3', 'SECRETARIA', 1200.50);
INSERT INTO CadFun 
VALUES (2, 'WILSON DE MACEDO', '3', 'PROGRAMADOR', 1050.00);
INSERT INTO CadFun 
VALUES (5, 'AUGUSTO SOUZA', '3', 'PROGRAMADOR', 1050.00);