SELECT * FROM cadfun;
SELECT DISTINCT DEPTO FROM cadfun;
DELETE FROM cadfun WHERE DEPTO='2';
SELECT * FROM cadfun;
SELECT DISTINCT DEPTO FROM cadfun;
DELETE FROM cadfun WHERE NOME = 'MARCELO SOUZA';
SELECT * FROM cadfun;
